function get_linear_gust_response(state_space_system, input_settings, gust_lengths, gust_intensities)
     list_indices = [input_settings.index.eta_tip input_settings.index.eta_dot_tip];
     if input_settings.rbm
        list_indices = [list_indices  input_settings.index.rbm];
     end
    ss_gust = ss(state_space_system.A,...
        state_space_system.B_gust,...
        state_space_system.C(list_indices, :), ...
        state_space_system.D_gust(list_indices, :), ...
        input_settings.dt);
    
    for i_length=1:length(gust_lengths)
        for i_intensity=1:length(gust_intensities)
            %% Get gust for specific length and intensity
            gust = get_1minuscosine_gust_input(gust_lengths(i_length), ...
                gust_intensities(i_intensity), ...
                input_settings.dt, ...
                input_settings.u_inf, ...
                input_settings.flight_time);
            %% Time Domain simulation
            output_gust_response = lsim(ss_gust, gust(:,2), gust(:,1));
            %% Write Results
            file_name =strcat('gust_response_L_',...
                num2str(gust_lengths(i_length)), ...
                '_I_', ...
                num2str(gust_intensities(i_intensity)), '_', ...
                input_settings.case_name);
            writematrix(output_gust_response, ...
                strcat('./linear_open_loop_results/', file_name, '.csv'));

        end
    end
end