function controller = design_LQR_controller(controller, num_known_control_inputs, ...
    num_aero_states, n_modes, n_rbm, list_modes, R_factor, delta_factor)
%design_LQR_controller Sets the Q and R matrices and generates the LQR gain
[controller.Q, controller.R] = define_Q_and_R_matrices_for_LQR(num_known_control_inputs, ...
            controller.C, ...
            num_aero_states, ...
            n_modes, ...
            n_rbm, ...
            list_modes, ...
            R_factor, ...
            delta_factor)
controller.K = dlqr(controller.A, controller.B_LQR, controller.Q, controller.R);
end