function controller = design_LQR_controller(controller, num_known_control_inputs, ...
    num_aero_states, n_modes, n_rbm, LQR_tuning)
%design_LQR_controller Sets the Q and R matrices and generates the LQR gain
[controller.Q, controller.R] = define_Q_and_R_matrices_for_LQR(num_known_control_inputs, ...
            num_aero_states, ...
            n_modes, ...
            n_rbm, ...
            LQR_tuning);
controller.K = dlqr(controller.A, controller.B_LQR, controller.Q, controller.R);
end