function controller = setup_controller_struct(linear_sys, LQR_tuning, ...
    num_inputs, num_aero_states, num_modes, num_rbm)
    controller.A = linear_sys.A;
    controller.B_LQR = linear_sys.B(:, 1:num_inputs);
    controller = design_LQR_controller(controller, ...
        num_inputs, ...
        num_aero_states, ...
        num_modes, ...
        num_rbm,...
        LQR_tuning);
end